refactor: Rounding issues revamp
Frankencoin-ZCHF/frankencoin-zchf.github.io pull request #12
Opened 2023-01-03 12:05 UTC by cbernard

2023-01-03 12:48 UTC, ManuBernard commented
not sure why the packagr.lock is included?

2023-01-03 19:24 UTC, cbernard commented
@ManuBernard Not sure why it shouldn't be included as there's a prettier update version

2023-01-04 08:38 UTC, ManuBernard requested changes

2023-01-04 08:38 UTC, ManuBernard commented on src/views/PositionAdjustView.vue
>        message: 'Insufficient collateral for the given amount.',
<img width="583" alt="image" src="https://user-images.githubusercontent.com/1818934/210512846-ea466050-3832-432e-8a99-b8c654c63486.png">

I receive this error message when i use the magic wand on the third field and have increased the amount of collateral.

2023-01-04 08:38 UTC, ManuBernard commented on src/components/SwapFieldInput.vue
> +    event.preventDefault();
<img width="149" alt="image" src="https://user-images.githubusercontent.com/1818934/210514379-8665a2c5-bdf5-4ff1-ab0d-eaded7aaca3f.png">

With this system, we cannot use "." but only "," I think this is too restrictive.

2023-01-04 08:38 UTC, ManuBernard commented on src/views/PositionPlaceBid.vue
>  const error = computed(() => {
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/1818934/210514651-61097b92-c211-4cbc-9e3b-a3d0e5a73167.png">


Shouldn't we handle this "bellow min bid" here ?

2023-01-04 09:44 UTC, cbernard commented on src/components/SwapField.vue
> +          {{ formatCommify(max) }}
We leave it like that for now to see what Luzius is thinking.

2023-01-04 09:58 UTC, cbernard commented on src/views/PositionAdjustView.vue
>        message: 'Insufficient collateral for the given amount.',
J'ai fix le soucis de decimale sur la magic wand collateral

2023-01-06 15:50 UTC, merged